### ISSUE TITLE
Magic needs explanation 

### ISSUE THREAD

**Issue by msangel** [petitparser/dart-petitparser-examples#1]
Hello!

I'm looking for some examples with petitparser that will allow me to create own programming language. I am Java developer itself. 
So the closest sample I found is the Lisp interpreter in this repo. And all the main magic about evaluation stuff happening here :
<img src="https://user-images.githubusercontent.com/773163/168432450-4337225c-22a5-46cc-a693-0b35420e2972.png" width=500/>
This looks like a recursive function that took an object with just two props `head` and `tail` and first calls _itself_ with `head` to create a function and then uses the resulting function and calls it with `tail`.
But can't get where the function creation actually happened, and how its evaluation was performed. Can be a bit of explanation on this? 

Thanks!

**Comment by renggli** [comment]
The highlighted code evaluates expressions like `(foo 1 2 3)`. 

The first line in the selection looks up the function to evaluate. It does so by evaluating `expr.head`. In the lines following the selection you can see that a `Name` like `foo` is simply looked up in the current environment.

The resulting Dart function is then evaluated with `expr.tail` as the arguments, in the example `1, 2, 3`. The function can be [a primitive](https://github.com/petitparser/dart-petitparser-examples/blob/main/lib/src/lisp/native.dart) or a custom function that was defined using `(define ...)` and that is recursively calling `eval` [again](https://github.com/petitparser/dart-petitparser-examples/blob/main/lib/src/lisp/native.dart#L51).

To see this in action step with the debugger through [one of the tests](https://github.com/petitparser/dart-petitparser-examples/blob/main/test/lisp_test.dart#L577).

**Comment by msangel** [comment]
Thanks! Now I see this. The sample has an index of all built-in functions like:
```dart
define(Name('+'), _plus);
```
And so in the first line it simply does lookup,  and the second is simply executing it with given here params. 
So `head` is function name and `tail` params. 
Like here:`(+ 123)` ==> `Cons((Name)  env['+'], dynamic args)`

Now I got this!
