### ISSUE TITLE
Extracting the Lisp example

### ISSUE THREAD

**Issue by amake** [petitparser/dart-petitparser-examples#5]
I have a need for a Lisp parser and evaluator. I was going to write one myself, but I realized that the example here is already probably better than what I would have come up with on my own.

I could make a package that consumes this one, but I don't want all the extra dependencies.

Am I best off taking the code from here and starting a separate project? Could I call it "petit_lisp"?

Since the code in this repo is MIT-licensed, I believe I am *allowed* to do so, so I suppose I am mostly asking about how people feel about it, or if there are better alternative approaches.

(Aside: What I actually need is a near-Elisp, so I will need to add lots of library functions e.g. to an `ElispEnvironment` and also make a few parsing changes. I also want to add a mechanism for interrupting evaluation after some time i.e. to prevent infinite loops. It looks like I can do all or most of this additively, but I'm not positive about that.)

**Comment by renggli** [comment]
Sure, take the code as a starting point and pick your own name, the license allows you to do that as long as you include the original copyright notice.

I am definitely also interested in improving this implementation (particularly macros), but this code serves merely as simple use-case of PetitParser and is not supposed to implement a specific Lisp standard. Likely the current implementation is closer to Scheme, because this is what I am most familiar with ...

**Comment by amake** [comment]
Thank you. As I've been playing with it, I find that the changes I need to make are not purely additive, so my initial idea of having a "generic core with Elisp overlay" seems unrealistic. I may have to explicitly specialize it for Elisp.

> Likely the current implementation is closer to Scheme, because this is what I am most familiar with ...

Yes, I started to feel the difference (Lisp-1 vs Lisp-2) when I accidentally rebound a function with a function argument. I love the simplicity of Scheme, and what I really need is just an Elisp-ish configuration language, so I'd like to stick with it as much as possible.

**Comment by amake** [comment]
I should ask explicitly: Do you object to me using the word "petit"? I am thinking something like "petit_lisp" or "petit_elisp".

**Comment by renggli** [comment]
Sure, that sounds good!

**Comment by amake** [comment]
OK, thank you. I will close as I don't think there's anything else to discuss.
